In [1]:
import pandas as pd
import numpy as np
from sqlalchemy import create_engine
import pandas as pd

In [2]:
def get_data(nums):
    dfs=[]
    URL='http://web.mta.info/developers/data/nyct/turnstile/turnstile_{}.txt'
    for i in nums:    
        URLs=URL.format(i)
        dfs.append(pd.read_csv(URLs))        
    return pd.concat(dfs)
nums=[160903,160910,160917]
get_data(nums)

,C/A,UNIT,SCP,STATION,LINENAME,DIVISION,DATE,TIME,DESC,ENTRIES,EXITS
0,A002,R051,02-00-00,59 ST,NQR456,BMT,08/27/2016,00:00:00,REGULAR,5799442,1966041
1,A002,R051,02-00-00,59 ST,NQR456,BMT,08/27/2016,04:00:00,REGULAR,5799463,1966044
2,A002,R051,02-00-00,59 ST,NQR456,BMT,08/27/2016,08:00:00,REGULAR,5799492,1966079
3,A002,R051,02-00-00,59 ST,NQR456,BMT,08/27/2016,12:00:00,REGULAR,5799610,1966155
4,A002,R051,02-00-00,59 ST,NQR456,BMT,08/27/2016,16:00:00,REGULAR,5799833,1966214
...,...,...,...,...,...,...,...,...,...,...,...
192873,TRAM2,R469,00-05-01,RIT-ROOSEVELT,R,RIT,09/16/2016,05:00:00,REGULAR,5554,271
192874,TRAM2,R469,00-05-01,RIT-ROOSEVELT,R,RIT,09/16/2016,09:00:00,REGULAR,5554,271
192875,TRAM2,R469,00-05-01,RIT-ROOSEVELT,R,RIT,09/16/2016,13:00:00,REGULAR,5554,271
192876,TRAM2,R469,00-05-01,RIT-ROOSEVELT,R,RIT,09/16/2016,17:00:00,REGULAR,5554,271
192877,TRAM2,R469,00-05-01,RIT-ROOSEVELT,R,RIT,09/16/2016,21:00:00,REGULAR,5554,271

In [4]:
NYPD_Complaint_Data=pd.read_csv('https://data.cityofnewyork.us/api/views/5uac-w243/rows.csv?accessType=DOWNLOAD')
NYPD_Complaint_Data

,CMPLNT_NUM,ADDR_PCT_CD,BORO_NM,CMPLNT_FR_DT,CMPLNT_FR_TM,CMPLNT_TO_DT,CMPLNT_TO_TM,CRM_ATPT_CPTD_CD,HADEVELOPT,HOUSING_PSA,...,TRANSIT_DISTRICT,VIC_AGE_GROUP,VIC_RACE,VIC_SEX,X_COORD_CD,Y_COORD_CD,Latitude,Longitude,Lat_Lon,New Georeferenced Column
0,758521794,67,NaN,03/07/2021,01:50:00,NaN,NaN,COMPLETED,NaN,NaN,...,NaN,18-24,BLACK,M,1008789,177637,40.654223,-73.911563,"(40.654223423000076, -73.91156340899995)",POINT (-73.91156340899995 40.654223423000076)
1,696896951,60,NaN,03/26/2021,18:40:00,NaN,NaN,COMPLETED,NaN,NaN,...,NaN,25-44,BLACK HISPANIC,M,987641,148923,40.575443,-73.987795,"(40.57544276900006, -73.98779476299995)",POINT (-73.98779476299995 40.57544276900006)
2,972479923,75,BROOKLYN,03/27/2021,15:55:00,03/27/2021,16:00:00,COMPLETED,NaN,NaN,...,NaN,25-44,BLACK,F,1020990,186549,40.678643,-73.867543,"(40.67864264400004, -73.867542755)",POINT (-73.867542755 40.67864264400004)
3,109344500,77,BROOKLYN,03/28/2021,11:10:00,03/28/2021,11:23:00,COMPLETED,NaN,NaN,...,NaN,UNKNOWN,UNKNOWN,D,1004507,182865,40.668584,-73.926980,"(40.66858395700007, -73.92697993199994)",POINT (-73.92697993199994 40.66858395700007)
4,673945415,23,NaN,03/29/2021,23:13:00,NaN,NaN,COMPLETED,NaN,NaN,...,NaN,25-44,WHITE HISPANIC,M,1000267,228200,40.793026,-73.942156,"(40.793026087000044, -73.94215617799993)",POINT (-73.94215617799993 40.793026087000044)
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
204641,154508455,121,STATEN ISLAND,04/03/2021,01:34:00,04/03/2021,01:37:00,COMPLETED,NaN,1287.0,...,NaN,25-44,BLACK,F,938890,170112,40.633487,-74.163427,"(40.633486765000036, -74.163427185)",POINT (-74.163427185 40.633486765000036)
204642,392278526,104,QUEENS,04/01/2021,23:00:00,04/02/2021,11:30:00,COMPLETED,NaN,NaN,...,NaN,25-44,WHITE HISPANIC,M,1014282,193283,40.697151,-73.891697,"(40.697151217000055, -73.89169705799998)",POINT (-73.89169705799998 40.697151217000055)
204643,730121906,34,MANHATTAN,03/20/2021,16:00:00,03/20/2021,16:30:00,COMPLETED,NaN,NaN,...,NaN,25-44,WHITE HISPANIC,M,1006513,253948,40.863683,-73.919513,"(40.86368344200008, -73.91951336999993)",POINT (-73.91951336999993 40.86368344200008)
204644,788230671,75,BROOKLYN,04/04/2021,04:10:00,04/04/2021,04:20:00,COMPLETED,NaN,NaN,...,NaN,18-24,WHITE HISPANIC,M,1013920,186247,40.677840,-73.893034,"(40.67784024200005, -73.89303352099995)",POINT (-73.89303352099995 40.67784024200005)
204645,906755938,7,MANHATTAN,03/27/2021,21:00:00,03/31/2021,21:30:00,COMPLETED,NaN,597.0,...,NaN,45-64,BLACK,F,987324,200564,40.717186,-73.988912,"(40.717186266000056, -73.98891235199994)",POINT (-73.98891235199994 40.717186266000056)

SQLalchemy

In [8]:
engine = create_engine("sqlite:///Users/hindsalem/data_base.db")

In [9]:
all_tables = engine.table_names()
all_tables

<ipython-input-9-94603f164bb3>:1: SADeprecationWarning: The Engine.table_names() method is deprecated and will be removed in a future release.  Please refer to Inspector.get_table_names(). (deprecated since: 1.4)
  all_tables = engine.table_names()

OperationalError: (sqlite3.OperationalError) unable to open database file
(Background on this error at: http://sqlalche.me/e/14/e3q8)

In [ ]:
doctors_data = pd.read_sql('SELECT * FROM NYPD;', engine)
doctors_data